global_frame: /map
robot_base_frame: /base_footprint
update_frequency: 1.0
static_map: true
rolling_window: false
track_unknown_space: true
allow_unknown: false
resolution: 0.05

plugins:
#  - {name: obstacles_laser,           type: "costmap_2d::ObstacleLayer"}
  - {name: static,                  type: "costmap_2d::StaticLayer"}
  - {name: inflation_global,               type: "costmap_2d::InflationLayer"}
