# goal coordinates
float32 x
float32 y
float32 z

string frame_id

# name of goal object
string obj_name

# height of goal object
float32 h

# width of goal object
float32 w

---
# Define the result

float32 x
float32 y
float32 z

---
# The internal state that the pickup action currently is in

float32 x
float32 y
float32 z
float32 distance